# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/dca3e5a7-203d-47b9-7097-54a54045f705/volume/rsync-recipes/libffi-3.3-on-osx, last modified Wed Apr 22 14:56:41 2020
# ------------------------------------------------

package:
    name: libffi
    version: '3.3'
source:
    fn: libffi-3.3.tar.gz
    patches:
        - patches/0001-check-for-existence-of-type-before-setting.patch
    sha1: 8df6cb570c8d6596a67d1c0773bf00650154f7aa
    url: ftp://sourceware.org/pub/libffi/libffi-3.3.tar.gz
build:
    number: '1'
    run_exports:
        - libffi >=3.3,<3.4.0a0
    string: h0a44026_1
requirements:
    build:
        - autoconf 2.69 pl526he370928_5
        - automake 1.16.1 pl526_0
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - clangxx 4.0.1 1
        - clangxx_osx-64 4.0.1 h22b1bf0_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libtool 2.4.6 h1de35cc_5
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
        - m4 1.4.18 h1de35cc_1
        - make 4.2.1 h3efe00b_1
        - perl 5.26.2 h4e221da_0
    host:
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
    run:
        - libcxx >=4.0.1
test:
    commands:
        - test -e $PREFIX/lib/libffi.a
        - test -e $PREFIX/lib/libffi.dylib
        - test -e $PREFIX/include/ffi.h
        - test -e $PREFIX/include/ffitarget.h
about:
    description: 'The libffi library provides a portable, high level programming interface

        to various calling conventions. This allows a programmer to call any

        function specified by a call interface description at run-time.

        '
    dev_url: https://github.com/libffi/libffi
    doc_url: https://sourceware.org/libffi/
    home: https://sourceware.org/libffi/
    license: Custom
    summary: A Portable Foreign Function Interface Library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - scopatz
        - stefan-balke
