# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/7c06bfcf-9a81-473f-7719-96d6abdc2721/volume/rsync-recipes/pip-20.0.2-python_3.8-on-osx, last modified Thu May  7 12:19:25 2020
# ------------------------------------------------

package:
    name: pip
    version: 20.0.2
source:
    patches:
        - 0001-Win32-Fix-Py_DEBUG-determination-in-_derive_abi-in-w.patch
    sha256: 7db0c8ea4c7ea51c8049640e8e6e7fde949de672bfa4949920675563a5a6967f
    url: https://pypi.io/packages/source/p/pip/pip-20.0.2.tar.gz
build:
    disable_pip: true
    entry_points:
        - pip = pip._internal.cli.main:main
    number: '3'
    string: py38_3
requirements:
    build:
        - patch 2.7.6 h1de35cc_1001
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.3 h0a44026_1
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - python 3.8.2 hf48f09d_13
        - readline 8.0 h1de35cc_0
        - setuptools 46.1.3 py38_0
        - sqlite 3.31.1 h5c1f38d_1
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
        - setuptools
        - wheel
test:
    commands:
        - pip -h
        - pip list
    imports:
        - pip
about:
    dev_url: https://github.com/pypa/pip
    doc_url: https://pip.pypa.io/en/stable/
    home: https://pip.pypa.io/en/stable/
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: PyPA recommended tool for installing Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
