# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/433b98b1-f3f1-4b60-63f0-579131149e9b/volume/rsync-recipes/sqlite-3.31.1-on-osx, last modified Tue Apr 21 14:33:30 2020
# ------------------------------------------------

package:
    name: sqlite
    version: 3.31.1
source:
    -   folder: amalgamated
        patches:
            - patches/applicable-to-amalgamated/0000-sqlite3-c-amalgamated.patch
            - patches/applicable-to-amalgamated/0001-expose_symbols.patch
        sha256: 62284efebc05a76f909c580ffa5c008a7d22a1287285d68b7825a2b6b51949ae
        url: https://www.sqlite.org/2020/sqlite-autoconf-3310100.tar.gz
build:
    number: '1'
    run_exports:
        - sqlite >=3.31.1,<4.0a0
    string: h5c1f38d_1
requirements:
    build:
        - autoconf 2.69 pl526he370928_5
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libtool 2.4.6 h1de35cc_5
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
        - m4 1.4.18 h1de35cc_1
        - make 4.2.1 h3efe00b_1
        - patch 2.7.6 h1de35cc_1001
        - perl 5.26.2 h4e221da_0
        - tk 8.6.8 ha441bb4_0
        - zlib 1.2.11 h1de35cc_3
    host:
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - ncurses 6.2 h0a44026_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - libedit >=3.1.20181209,<3.2.0a0
        - ncurses >=6.2,<7.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - sqlite3 --version
        - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
        - test -f $PREFIX/include/sqlite3.h
about:
    description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

        public-domain, SQL database engine.It is the most used database engine

        in the world.

        '
    dev_url: https://github.com/mackyle/sqlite
    doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
    doc_url: http://www.sqlite.org/docs.html
    home: http://www.sqlite.org/
    license: Public-Domain (http://www.sqlite.org/copyright.html)
    license_url: http://www.sqlite.org/copyright.html
    summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - snorfalorpagus
